### ISSUE TITLE
https://github.com/Andrii97/TPPS/blob/master/EuroDiffusion/src/main/java/ua/kpi/EuroDiffusionSimulation.java#L61

### ISSUE THREAD

**Issue by IanaKhitsko** [Andrii97/TPPS#2]
if (!countries[i].isComplete())
                result &= checkCountryComplete(countries[i]);
===
consider changing to this...
for(...){
if (!countries[i].isComplete() && !checkCountryComplete(countries[i]))
   return false;
}
return true;

**Comment by AndriiSeverin** [comment]
@IanaKhitsko 
I think it is a good idea. However, it won't work in this way because the proposed code modification will not change the status of countries that follow by first non-complete country (if one of the followed countries becomes complete in the current day).
I will change it in this way:
for(...){
if (!countries[i].isComplete() && !checkCountryComplete(countries[i]))
result = false;
}
return result;

If from your point of view it is not good, just let me know how it will be better.
